name: PR Check

on:
  pull_request:
    branches:
      - main

jobs:
  pr-check:
    runs-on: ubuntu-latest
    
    steps:
      - name: checkout repository
        uses: actions/checkout@v4

      - name: show pr branch name
        run: echo "The pull request branch name is ${{ github.head_ref }}"



